version: '3.8'
services:
  jupyter-client:
    image: python:3.9-slim
    container_name: jupyter-client
    platform: linux/amd64
    depends_on:
      - broker1-kr
      - broker2-kr
    command: >
      bash -c "pip install jupyter pandas pyarrow confluent-kafka faust &&
               jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --NotebookApp.token=''"
    ports:
      - "8888:8888"
    volumes:
      - .:/workspace
      - ./yellow_partitioned:/workspace/yellow_partitioned
      - ./fhvhv_partitioned:/workspace/fhvhv_partitioned

    working_dir: /workspace

